name: smart_helmet_mobile
description: Smart Helmet mobile application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.2
  google_maps_flutter: ^2.9.0
  local_auth: ^2.3.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
